"""Añadir columna download_count a download_link

Revision ID: 23f37fecc97c
Revises: 5dcef1bcb2bd
Create Date: 2024-08-21 01:34:15.487862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f37fecc97c'
down_revision = '5dcef1bcb2bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('download_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_link', schema=None) as batch_op:
        batch_op.drop_column('download_count')

    # ### end Alembic commands ###
