"""Add created_at field to Product model

Revision ID: 6961a2b0a44c
Revises: 4daa1b3ababd
Create Date: 2024-08-24 12:31:17.487577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6961a2b0a44c'
down_revision = '4daa1b3ababd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    # ### end Alembic commands ###

    # Actualizar el valor de created_at para las filas existentes
    op.execute('UPDATE product SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL')



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
